### ISSUE TITLE
asyncio_redis.Pool.create error ?

### ISSUE THREAD

**Issue by rfyiamcool** [jonathanslenders/asyncio-redis#103]
```
import asyncio
import asyncio_redis

connection = asyncio_redis.Pool.create(host='localhost', port=6379, poolsize=10)

@asyncio.coroutine
def example():
    # Set a key
    yield from connection.set('my_key', 'my_value')
    # When finished, close the connection pool.
    connection.close()
```

[root@ubuntu:~]#python3.5 r.py
Traceback (most recent call last):
  File "r.py", line 15, in <module>
    loop.run_until_complete(example())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "r.py", line 9, in example
    yield from connection.set('my_key', 'my_value')
AttributeError: 'generator' object has no attribute 'set'

why   cann't   put  `asyncio_redis.Pool.create`  in other places ？   thanks you .

**Comment by jonathanslenders** [comment]
``Pool.create`` is a coroutine. This means that you need to put "await" in front of it to get the actual result.

```python
connection = await asyncio_redis.Pool.create(host='localhost', port=6379, poolsize=10)
```
Of course, this means also that this line has to be moved inside another coroutine. (E.g, in the "example" function.)
