### ISSUE TITLE
Broken on python 3.7.0

### ISSUE THREAD

**Issue by toyg** [jonathanslenders/asyncio-redis#124]
After `pip install asyncio_redis`, the module fails to import:

```python
>>> import asyncio_redis
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/myprj/venv/lib/python3.7/site-packages/asyncio_redis/__init__.py", line 4, in <module>
    from .connection import *
  File "/myprj/venv/lib/python3.7/site-packages/asyncio_redis/connection.py", line 14
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax
```

**Comment by rafa-acioly** [comment]
@mikekeda there is a date to a new release?

**Comment by jonathanslenders** [comment]
Hi everyone, I did release it some time ago, but forgot to notify this thread.
Let me know if it's missing certain fixes.

**Comment by toyg** [comment]
Yup, looks fine.
