### ISSUE TITLE
AssertionError when trying to hmset

### ISSUE THREAD

**Issue by kimvais** [jonathanslenders/asyncio-redis#57]
This code:
```python
import asyncio

import asyncio_redis
from asyncio_redis.encoders import BytesEncoder


@asyncio.coroutine
def test():
    conn = yield from asyncio_redis.Connection.create(host='localhost', port=6379, db=0,
                                                      encoder=BytesEncoder())
    d = dict(a=1, b=2)
    yield from conn.hmset(b'foo', d)
    conn.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(test())

```
throws:

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    loop.run_until_complete(test())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 268, in run_until_complete
    return future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 236, in _step
    result = next(coro)
  File "test.py", line 12, in test
    yield from conn.hmset(b'foo', d)
  File "/Users/kimvais/py34/lib/python3.4/site-packages/asyncio_redis/protocol.py", line 655, in wrapper
    result = yield from method(protocol_self, *a, **kw)
  File "/Users/kimvais/py34/lib/python3.4/site-packages/asyncio_redis/protocol.py", line 1692, in hmset
    assert isinstance(k, self.native_type)
AssertionError
Task was destroyed but it is pending!
task: <Task pending coro=<_reader_coroutine() running at /Users/kimvais/py34/lib/python3.4/site-packages/asyncio_redis/protocol.py:919> wait_for=<Future pending cb=[Task._wakeup()]>>
```

**Comment by kimvais** [comment]
Ah, nevermind, 
```
d = {b'a':b'1', b'b':b'2'}
```
works

**Comment by jonathanslenders** [comment]
Yes, both key and values have to be bytes. If you want to have integers, you should build an abstraction layer on top of it.

Nice you figured it out! :)
