### ISSUE TITLE
Is it possible to return Error on connecting to not running Redis Server?

### ISSUE THREAD

**Issue by shongololo** [jonathanslenders/asyncio-redis#69]
I am creating a connection pool per:
<code>
my_connection = yield from asyncio_redis.Pool.create(host... port... poolsize...)
</code>

When Redis Server is not running, then the code hangs at the yield from. Is it possible to add a timeout or Error to the effect that Redis is not running?

**Comment by zadoev** [comment]
Same problem, when server is inactive i got no control to main flow after yield. 

```python
def init2(loop):
    print("connecting")
    redis_connection = yield from asyncio_redis.Pool.create(
        host=settings.REDIS_SERVER,
        port=6379,
        poolsize=10,
        loop=loop
    )
    print('got control here')

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(init2(loop))
    loop.run_forever()
```
LOGS: 

/home/user/project/venv/bin/python /home/user/project/src/app-server.py
connecting
DEBUG:asyncio:Using selector: EpollSelector
INFO:asyncio_redis:Connecting to redis
DEBUG:asyncio:Get address info 192.168.1.200:6379, type=<SocketKind.SOCK_STREAM: 1>
DEBUG:asyncio:Getting address info 192.168.1.200:6379, type=<SocketKind.SOCK_STREAM: 1> took 2.529 ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.1.200', 6379))]
DEBUG:asyncio:poll took 2.053 ms: 1 events
DEBUG:asyncio:connect <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 0)> to ('192.168.1.200', 6379)
INFO:asyncio:poll took 2996.282 ms: 1 events
INFO:asyncio_redis:Connecting to redis failed. Retrying in 0 seconds
INFO:asyncio_redis:Connecting to redis
DEBUG:asyncio:Get address info 192.168.1.200:6379, type=<SocketKind.SOCK_STREAM: 1>
DEBUG:asyncio:Getting address info 192.168.1.200:6379, type=<SocketKind.SOCK_STREAM: 1> took 0.073 ms: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.1.200', 6379))]
DEBUG:asyncio:connect <socket.socket fd=7, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 0)> to ('192.168.1.200', 6379)
Traceback (most recent call last):
  File "/home/cd/data/projects/python/wtr-all-superproject/chat/src/chat-server.py", line 58, in <module>
    loop.run_until_complete(init2(loop))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 304, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_forever
    self._run_once()
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1116, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.4/selectors.py", line 432, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
DEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>

**Comment by achimnol** [comment]
I think you could use [`asyncio.wait_for()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for) with timeout parameter.

**Comment by shongololo** [comment]
Good suggestion, will give it a shot.
