### ISSUE TITLE
SPOP on non-existing key should be None or an explicit exception

### ISSUE THREAD

**Issue by achimnol** [jonathanslenders/asyncio-redis#76]
```python
#! /usr/bin/env python3                                                                                                                                                                                   
import asyncio, asyncio_redis as aioredis

@asyncio.coroutine
def go():
    conn = yield from aioredis.Pool.create(host='127.0.0.1', port=6379)
    v = yield from conn.spop('some-non-existent-key')
    print(v)
    conn.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(go())
    loop.close()
```
The above code gives an AssertionError, which is somewhat unexpected:
```
Traceback (most recent call last):
  File "spop_test.py", line 14, in <module>
    loop.run_until_complete(go())
  File "/Users/joongi/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/Users/joongi/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/Users/joongi/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "spop_test.py", line 8, in go
    v = yield from conn.spop('some-non-existent-key')
  File "/Users/joongi/homebrew/lib/python3.4/site-packages/asyncio_redis/protocol.py", line 657, in wrapper
    result = yield from post_process(protocol_self, result)
  File "/Users/joongi/homebrew/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/coroutines.py", line 141, in coro
    res = func(*args, **kw)
  File "/Users/joongi/homebrew/lib/python3.4/site-packages/asyncio_redis/protocol.py", line 378, in bytes_to_native
    assert isinstance(result, bytes)
AssertionError
Exception ignored in: Task was destroyed but it is pending!
task: <Task pending coro=<_reader_coroutine() running at /Users/joongi/homebrew/lib/python3.4/site-packages/asyncio_redis/protocol.py:919> wait_for=<Future pending cb=[Task._wakeup()]>>
```
I think the result should be `None`, or an explicit exception such as "key does not exist".

**Comment by jonathanslenders** [comment]
This should fix it: https://github.com/jonathanslenders/asyncio-redis/pull/79

**Comment by jonathanslenders** [comment]
Merged.
